### ISSUE TITLE
Export result is empty

### ISSUE THREAD

**Issue by Dadatata-JZ** [choosehappy/QuPathGeoJSONImportExport#1]
Hi Andy, 

Thanks for sharing this. I copied your script to QuPath Script Editor, but got empty list in my exported json file. I don't have much experience with QuPath. I assume these annotations on the left should be included in object annotationMeasurements but they are not. 

Please kindly give me some suggestions. Thank you in advance. 

![Screen Shot 2021-07-23 at 12 19 41 PM](https://user-images.githubusercontent.com/31292151/126811842-dbedecfb-9fac-4b11-b7df-fb9f336788b2.png)

**Comment by choosehappy** [comment]
take a look at the associated blog post:
http://www.andrewjanowczyk.com/exporting-and-re-importing-annotations-from-qupath-for-usage-in-machine-learning/

in particular the section called: "QuPath Type"

**Comment by Dadatata-JZ** [comment]
Sorry for missing such handy notes! Thanks

**Comment by Dadatata-JZ** [comment]
Hi Andy, 

An additional question, do you by any chance know how to export a batch of annotations files? I have a list of whole slide images with annotations and want to export them in jsons for deep learning labelling. However, opening them in QuPath GUI manually is quite time-consuming. 

Thanks

**Comment by choosehappy** [comment]
if you create a project and put all your files into it, you will be able to click run for project:

![image](https://user-images.githubusercontent.com/9681868/126814047-5ac1e2c4-0e85-436b-b511-16100f28d4be.png)


this will run the code once per file


if you're interested in taking a pure python approach, you can check out paquo: https://github.com/bayer-science-for-a-better-life/paquo
